[[drones]]
id = 0
connected_drone_ids = [1, 20]
pdr = 0.05

[[drones]]
id = 1
connected_drone_ids = [0]
pdr = 0.03

[[drones]]
id = 2
connected_drone_ids = [30]
pdr = 0.03

[[clients]]
id = 20
connected_drone_ids = [0]

[[servers]]
id = 30
connected_drone_ids = [2]
