[[drones]]
id = 1
connected_drone_ids = [2, 3]
pdr = 0.05

[[drones]]
id = 2
connected_drone_ids = [1,3,4]
pdr = 0.03

[[drones]]
id = 3
connected_drone_ids = [2,1,4]
pdr = 0.14

[[clients]]
id = 4
connected_drone_ids = [3, 2]

[[clients]]
id = 5
connected_drone_ids = [1]

[[servers]]
id = 6
connected_drone_ids = [2,3]
