[[drones]]
id = 1
connected_drone_ids = [20, 30, 31]
pdr = 0.0

[[drones]]
id = 2
connected_drone_ids = [30, 31]
pdr = 0.0

[[clients]]
id = 20
connected_drone_ids = [1]

[[servers]]
id = 30
connected_drone_ids = [1, 2]

[[servers]]
id = 31
connected_drone_ids = [1, 2]
