name: Fmt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Give GitHub Actions access
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.DRONE_PRIVATE_KEY }}

    - name: Format
      run: cargo fmt --all --quiet

    - name: Clippy
      run: cargo clippy -- -W clippy::pedantic
