name: Fmt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up SSH for private repo
      run: |
        - name: Set up SSH for private repo
        run: |
          mkdir -p ~/.ssh
          # Start the ssh-agent
          eval "$(ssh-agent -s)" >
          # Add private SSH key
          ssh-add ${{ secrets.ACTIONS_SSH_KEY }}
          # Add GitHub to the list of known hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Format
      run: cargo fmt --all --quiet
    - name: Clippy
      run: cargo clippy -- -W clippy::pedantic
