name: Fmt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up SSH for private repo
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ACTIONS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Start the ssh-agent
        eval "$(ssh-agent -s)"
        # Add private SSH key
        ssh-add ~/.ssh/id_rsa
    - name: Format
      run: cargo fmt --all --quiet
    - name: Clippy
      run: cargo clippy -- -W clippy::pedantic
