name: Cargo Build & Test

on:
  push:
  pull_request:
  
env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    - name: Give GitHub Actions access
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: |
          ${{ secrets.DRONE_PRIVATE_KEY }}
          ${{ secrets.CLIENT_SERVER_TESTING_PRIVATE_KEY }}

    - name: Test
      run: cargo test --verbose --no-fail-fast --color always
